<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- Font Awesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- GSAP CDN Link -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.2/gsap.min.js"></script>

    <!-- Fonts CDN Link -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <title>Fragnance | About Us</title>
</head>

<body>

    <!-- Navbar Code Include  -->

    <?php $this->load->view('include/Navbar'); ?>


    <!-- About Us Code Start  -->

    <div class="container">
        <h1 class="montserrat text-center my-5 fw-bold">Privacy Policy</h1>
        <div class="row mb-5">
            <div class="col-md-9 mx-auto" style="text-align: justify;">
                <p class="montserrat lh-lg">
                    This Privacy Policy (“Policy”) is published in accordance with the provisions of Rule 3(1) of the
                    Information Technology (Intermediaries Guidelines) Rules, 2011. The Policy is an ‘electronic record'
                    as contemplated under section 2(t) of the Information Technology Act, 2000, and the rules. This
                    Policy, being an electronic record, is generated by a computer system and does not require any
                    physical or digital signature.
                </p>

                <h5 class="montserrat fw-bold mt-5">INTRODUCTION</h5>
                <p class="montserrat lh-lg">
                    The online store www.fragnance.in ("Online Store") is owned and operated by Fragnance Private
                    Limited, a private limited company incorporated under the laws of India, having its registered
                    office at Block 7 & 8, Garden View, Sindhu Bhawan Marg, Cafe Flambe, Bodakdev, Ahmedabad, Gujarat -
                    380054, India.
                </p>
                <p class="montserrat lh-lg">
                    Users are requested to read and understand the Policy very carefully before using or accessing the
                    Online Store. Through this Policy, Fragnance Private Limited intends to convey the manner in which
                    the user's information is collated and used by Fragnance Private Limited while providing the
                    services of the Online Store. This Policy is binding on every user of the Online Store, and users
                    who do not agree with the terms of this Policy should not use or access the Online Store.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited reserves its right to change, edit, alter, amend, modify, review, revise,
                    or substitute this Policy with or without notice. By using the Online Store, users signify they have
                    carefully read, understood, and agree to be bound by this Policy, and the users expressly and
                    voluntarily accept this Policy, including any change, modification, or substitution made to the
                    Policy from time to time. Fragnance Private Limited reserves its right to refuse services to any
                    user who does not accept or violates the terms of this Policy.
                </p>

                <h5 class="montserrat fw-bold mt-5">USER INFORMATION</h5>
                <p class="montserrat lh-lg">
                    ‘User information' for the purpose of this Policy includes the user's personal information that can
                    be used to uniquely identify or contact a single person, including name, email address, residential
                    address, phone number, photograph, and other information collected by Fragnance Private Limited to
                    provide specific services to the user through the Online Store. The user has the option not to
                    provide User Information if the user wishes not to avail of the specific service for which the User
                    Information is required.
                </p>
                <p class="montserrat lh-lg">
                    If any user is providing any User Information on behalf of any corporation, company, institution,
                    association, or other entity, the user should be authorized by such corporation, company,
                    institution, association, or other entity to provide such information to Fragnance Private Limited.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited collects information from the user when creating a user account or when
                    the user is browsing for products, transacting an online purchase of products through the Online
                    Store, or while posting comments, uploading content, participating in any offers or contests,
                    availing special gifts, or communicating with customer support by phone, email, or otherwise.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited receives, scrutinizes, and stores User Information for security and
                    technical reasons such as IP address, login ID, email address, password, device connection
                    information, transaction history, date, time, and duration of session on the Online Store.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited automatically receives the URL of the site from which a user came and the
                    site to which the user goes when the user leaves the Website. The Online Store receives the IP
                    address of the user's computer and the type of web browser a user is using, email patterns, etc.
                    Fragnance Private Limited will occasionally ask the user to complete optional online surveys. These
                    surveys may ask the user for contact information and demographic information (e.g., zip code, age,
                    or income level).
                </p>
                <p class="montserrat lh-lg">
                    Sometimes the Online Store uses cookies so that the Online Store can provide the user with more
                    customized information when the user returns to the Online Store. "Cookies" are used to store user
                    preferences and to track user trends, so as to enhance the user's interactive experience and
                    generally improve the Online Store's services to the user. The user can set the browser to notify
                    the user when the user is sent a "cookie", giving the user the chance to decide whether or not to
                    accept it. If the user accepts a "cookie", the user agrees to the use of any User Information
                    collected by the Online Store using that cookie. The user may update their profile information at
                    any time on the Online Store.
                </p>
                <p class="montserrat lh-lg">
                    The user can add or update the User Information on a regular basis. When the user updates the User
                    Information, Fragnance Private Limited will keep a copy of the prior version for its records.
                </p>

                <h5 class="montserrat fw-bold mt-5">USE OF INFORMATION & DISCLOSURE</h5>
                <p class="montserrat lh-lg">
                    The User Information is primarily used by Fragnance Private Limited to facilitate a better,
                    customized, and convenient use of the Online Store's services. The User Information is used by
                    Fragnance Private Limited inter alia to (i) respond to the user's queries, requests, and inquiries;
                    (ii) update new features of the Online Store; (iii) improve and customize the Online Store's
                    service; (iv) detect and prevent fraud and abuse of the Online Store; (v) examine the identity of
                    the users and the authenticity of offers, delivery, or transfer of offers, etc.; (vi) administer the
                    Online Store; (vii) inform any change in the Terms of Use, this Policy, or the Terms and Conditions
                    of Sale; (viii) send surveys and marketing communications that Fragnance Private Limited believes
                    may be of interest to the user; (ix) personalize the user's experience on the Online Store by
                    presenting advertising, products, and offers tailored for the user; (x) help the user address its
                    problems with the Online Store, including addressing any technical problems; (xi) complete and
                    fulfill the user's purchase, process payments, communicate with the user regarding the user's
                    purchase, and provide the user with related customer service; and (xii) protect the integrity of the
                    Online Store.
                </p>
                <p class="montserrat lh-lg">
                    User Information is used and disclosed if required to do so by law or in the good faith belief that
                    such disclosure is reasonably necessary to respond to notices, court orders, or other legal
                    processes. Fragnance Private Limited may disclose User Information to law enforcement officers,
                    third-party rights owners, or others if, in its opinion, it is reasonably necessary to enforce the
                    Online Store's Terms of Use, this Policy, and Terms and Conditions of Sale. Fragnance Private
                    Limited will share some or all of the User Information with another entity should Fragnance Private
                    Limited merge with, or be acquired by, that entity or receive investments from that entity.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited may disclose aggregated information about the use of the Website, but it
                    will never contain User Information that will identify a single user.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited does not trade or sell User Information in any manner, except as specified
                    in this Policy or if express consent is sought from the user.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited understands that the User Information is very crucial and important for
                    the user. The user agrees and acknowledges that the User Information is disclosed or shared with:
                    (i) third-party vendors for delivery of the products ordered through the Website, (ii) third-party
                    service providers engaged by Fragnance Private Limited to perform the services on Fragnance Private
                    Limited's behalf, (iii) third-party service providers for the purpose of the Website's security,
                    maintenance, repair, or other technical reasons.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited may, if the user so chooses, send direct advertisement mailers to the user
                    at the address given by the user. The user has the option to opt out of this direct mailer by
                    clicking the unsubscribe link option attached to the e-mail.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited respects the user'?includes privacy, and if the user does not want to receive
                    e-mails or other communications from Fragnance Private Limited, the user may inform the same to our
                    customer care service.
                </p>


                <h5 class="montserrat fw-bold mt-5">SECURITY & USER RESTRICTION</h5>
                <p class="montserrat lh-lg">
                    Fragnance Private Limited implements standard measures to protect against unauthorized access to and
                    unlawful interception of the User Information. However, no internet site can fully eliminate
                    security risks.
                </p>
                <p class="montserrat lh-lg">Fragnance Private Limited endeavors to take all measures to protect the
                    security, integrity, and confidentiality of the User Information against unauthorized breach and
                    hacking. For the purpose of checking possible vulnerabilities and attacks, Fragnance Private Limited
                    may conduct periodic internal reviews of data and security measures on the Website.</p>

                <p class="montserrat lh-lg">Fragnance Private Limited may use such software as it determines is best for
                    maintaining security. However, the internet is not an absolutely secure environment, and the Website
                    cannot ensure or warrant a 100% security of the User Information.</p>

                <p class="montserrat lh-lg">If any user is provided with any identification code, password, or any other
                    piece of information as part of the Website's security procedure, the user should treat such
                    information as confidential, and the user should not disclose it to any third party, including other
                    users. To prevent third-party access to the Website, the user should sign out from the user account
                    after availing the services through the Website.</p>

                <p class="montserrat lh-lg">Fragnance Private Limited has the right to disable the identification code
                    or password, whether chosen by any user or allotted by Fragnance Private Limited, at any time, if
                    the user fails to comply with instructions, terms, conditions, or policies of Fragnance Private
                    Limited.</p>

                <p class="montserrat lh-lg">The user is solely responsible for the activities that occur under the
                    user's account, including the confidentiality of the user's password, and Fragnance Private Limited
                    is not responsible for the same. While using and accessing the Website, the user is responsible for
                    maintaining the confidentiality of the user's account and for restricting access to the user's
                    computer or other system or equipment through which the user uses and accesses the Website.</p>

                <p class="montserrat lh-lg">Fragnance Private Limited shall not be held responsible for any loss,
                    damage, or misuse of the User Information if such loss, damage, or misuse is attributable to a Force
                    Majeure Event. A "Force Majeure Event" means any event that is beyond the reasonable control of
                    Fragnance Private Limited and includes, without limitation, fire, flood, explosion, acts of God,
                    civil commotion, strikes, lockouts or industrial action of any kind, riots, insurrection, war, acts
                    of government, power failure, sabotage, computer hacking, unauthorized access to computer data and
                    storage device, system failure, virus, attacks, bugs, computer crashes, breach of security, and
                    encryption.</p>


                <h5 class="montserrat fw-bold mt-5">THIRD PARTY WEBSITES AND LINKS</h5>
                <p class="montserrat lh-lg">
                    The Website may provide or be linked with other websites and advertisements. Fragnance Private
                    Limited is in no way responsible for the privacy practices or content of such websites. The linked
                    websites or advertisers are not necessarily under the control of Fragnance Private Limited, and
                    Fragnance Private Limited expressly disclaims all liability associated with the content and the use
                    of such websites and advertisements. Display of any third-party advertisements on the Website shall
                    not be construed as an endorsement or promotion of any products or services by Fragnance Private
                    Limited. The user should read the privacy policy of each and every linked website, and any access or
                    use of the linked websites is entirely at the user's own risk.
                </p>

                <p class="montserrat lh-lg">
                    Fragnance Private Limited is not responsible for any direct, indirect, solicited, or unsolicited
                    communication made by any of these linked third-party websites or advertisers or their respective
                    agents or representatives to the users, including by telephone, email, mobile phones, and facsimile.
                </p>

                <p class="montserrat lh-lg">
                    These linked third-party websites and advertisers may use various technologies to receive the user's
                    IP address and personal information. The third-party advertisers may also use cookies, JavaScript,
                    web beacons, and other technologies to gauge the effectiveness of their advertisements and to
                    personalize advertising experience and content.
                </p>

                <p class="montserrat lh-lg">
                    Fragnance Private Limited does not have any control over the cookies or technologies that
                    advertisers or websites may use, and the user should contact them directly for more information
                    about their privacy practices and policies.
                </p>

                <p class="montserrat lh-lg">
                    Based on the User Information, including the nature of products purchased by the user through the
                    Online Store, Fragnance Private Limited may display personalized third-party advertisements on the
                    Online Store. When the user clicks on the advertisement link, the third-party advertisers may assume
                    that the user has met the criteria that were used to personalize the advertisement. The user
                    acknowledges and agrees that in no event is Fragnance Private Limited responsible to the user
                    accessing the services of third-party advertisers or other websites.
                </p>


                <h5 class="montserrat fw-bold mt-5">GENERAL TERMS</h5>
                <p class="montserrat lh-lg">This Policy is to be read in conjunction with and shall be deemed to be part
                    of the Online Store's Terms of Use and Terms and Conditions of Sale.</p>

                <p class="montserrat lh-lg">The User Information resides in Fragnance Private Limited's database for a
                    certain period of time even after the user ceases to use or access the Online Store, and in such
                    cases, Fragnance Private Limited is not liable for any usage of the User Information after the user
                    ceases to use or access the Online Store.</p>

                <p class="montserrat lh-lg">The Users agree and acknowledge that User Information collated through the
                    Online Store could be stored and processed in any other country across the world. The users
                    acknowledge that for effective provision of the Online Store's services in respective territories,
                    including territories outside India, the User Information may be stored or processed by trusted
                    third parties. Whenever the User Information is shared with trusted third parties in countries
                    outside India, Fragnance Private Limited endeavors that the User Information is transferred in
                    accordance with the applicable laws of India.</p>

                <p class="montserrat lh-lg">The user should be aware that the User Information or other data provided to
                    the Online Store for availing the services or transacting through the Online Store could be read,
                    collected, or used by other users or third parties, in which case the User Information might be used
                    for sending unsolicited messages or communications for which Fragnance Private Limited is not
                    responsible.</p>

                <p class="montserrat lh-lg">The user agrees and acknowledges Fragnance Private Limited's right to
                    utilize the user's posts, contents, information, and other personal data for the purpose of
                    providing services through the Online Store. The contents on the Website may contain comments,
                    posts, and reviews posted by the users which may be public and searchable on the internet, in which
                    case the user's comments, posts, reviews, and information and personal data provided to the Online
                    Store may be viewed by other users, and Fragnance Private Limited cannot guarantee that other users
                    or third parties have not made copies of or used the ideas and information that the user has shared
                    on the Online Store.</p>


                <h5 class="montserrat fw-bold mt-5">QUESTIONS AND CONTACT INFORMATION</h5>
                <p class="montserrat lh-lg">If you would like to correct, amend, or delete any personal information we
                    have about you, or simply want more information, contact our Privacy Compliance Officer at
                    <a href="mailto:hi@fragnance.in">hi@fragnance.in</a>
                </p>



                <h5 class="montserrat fw-bold mt-5">GRIEVANCE OFFICER</h5>
                <p class="montserrat lh-lg">GRIEVANCE OFFICER<br>The name and contact details of the Grievance Officer
                    to handle any complaints in relation to the sale of Products or use of this Website are provided
                    below. All complaints will be acknowledged within 48 hours (Working Days), and will be addressed no
                    later than 1 month from the date of complaint received.</p>

                <p class="montserrat lh-lg">Name: Govind Mishra<br>Email: <a
                        href="mailto:govind.mishra@fragnance.in">govind.mishra@fragnance.in</a><br>Time:
                    Monday-Saturday (From 11:00 AM to 6:00 PM)</p>

                <p class="montserrat lh-lg">The user shall not assign its rights or obligations under these Terms and
                    the Privacy Policy to a third party.</p>

            </div>
        </div>

    </div>

    <!-- Footer Code Include  -->

    <?php $this->load->view('include/Footer'); ?>

</body>

</html>