<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- Font Awesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- GSAP CDN Link -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.2/gsap.min.js"></script>

    <!-- Fonts CDN Link -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <title>Fragnance | Terms And Conditions</title>
</head>

<body>

    <!-- Navbar Code Include  -->

    <?php $this->load->view('include/Navbar'); ?>


    <!-- About Us Code Start  -->

    <div class="container">
        <h1 class="montserrat text-center my-5 fw-bold">Terms & Conditions</h1>
        <div class="row mb-5">
            <div class="col-md-9 mx-auto" style="text-align: justify;">
                <p class="montserrat lh-lg">This Is An Electronic Record In Terms Of Information Technology Act, 2000
                    And Rules There Under As Applicable And The Amended Provisions Pertaining To Electronic Records In
                    Various Statutes As Amended By The Information Technology Act, 2000. This Electronic Record Is
                    Generated By A Computer System And Does Not Require Any Physical Or Digital Signatures.
                </p>

                <h5 class="montserrat fw-bold mt-5">Welcome to Fragnance.</h5>
                <p class="montserrat lh-lg">
                    Fragnance provides the content and services available on this website to you subject to the
                    following Terms and Conditions and other terms and conditions and policies which you may find
                    throughout our website in connection with certain customer service, features or functionality as
                    well as promotions, all of which are considered to be a part of and included within these Terms and
                    Conditions. By accessing or using this website, you are acknowledging that you have read,
                    understood, and you agree, without any limitation or qualification, to be bound by these Terms and
                    Conditions in this Agreement.
                </p>

                <h5 class="montserrat fw-bold mt-5">Privacy</h5>
                <p class="montserrat lh-lg">
                    To understand our privacy practices, please review our Privacy Policy.
                </p>

                <h5 class="montserrat fw-bold mt-5">Payment Policy</h5>
                <p class="montserrat lh-lg">
                    To understand the purchase processes of our products, please refer to our Payment Policy.
                </p>

                <h5 class="montserrat fw-bold mt-5">Products And Services For Personal Use</h5>
                <p class="montserrat lh-lg">
                    Any products or services provided to you on this website are for personal use only. You are not
                    allowed to sell or resell any of the products, services, or samples thereof, you receive from us. We
                    reserve the right, with or without notice, to cancel or reduce the quantity of any products or
                    services to be provided to you that we believe, in our sole discretion, may result in the violation
                    of our Terms and Conditions.
                </p>

                <h5 class="montserrat fw-bold mt-5">Accuracy Of Information</h5>
                <p class="montserrat lh-lg">
                    We try to be as accurate as possible when describing our products on the website. However, except as
                    required by applicable law, we do not warrant that the product descriptions, colors, information, or
                    other content available on the website are accurate, complete, reliable, current, or error-free.
                </p>

                <h5 class="montserrat fw-bold mt-5">Intellectual Property</h5>
                <p class="montserrat lh-lg">
                    All information and content available on the website and its "look and feel," including but not
                    limited to trademarks, logos, service marks, text, graphics, logos, button icons, images, audio
                    clips, data compilations, and the compilation and organization thereof (collectively, the "Content")
                    is the property of Fragnance, our Affiliates, partners, or licensors, and is protected by laws of
                    India, including laws governing all applicable forms of intellectual property.
                </p>

                <h5 class="montserrat fw-bold mt-5">Limited Licenses</h5>
                <p class="montserrat lh-lg">
                    We grant you a limited, revocable, and non-exclusive license to access and make personal use of the
                    Fragnance website. This limited license does not include the right to: (a) frame or utilize framing
                    techniques to enclose the website or any portion thereof; (b) republish, redistribute, transmit,
                    sell, license or download the website or any and/or all Content (except caching or as necessary to
                    view the website); (c) make any use of the website or any and/or all Content other than personal
                    use; (d) modify, reverse engineer or create any derivative works based upon either the website or
                    any and/or all Content; (e) collect account information for the benefit of yourself or another
                    party; (f) use any meta tags or any other "hidden text" utilizing any and/or all Content; or (g) use
                    software robots, spiders, crawlers, or similar data gathering and extraction tools, or take any
                    other action that may impose an unreasonable burden or load on our infrastructure. You must retain,
                    without modification, all proprietary notices on the website or affixed to or contained in the
                    website.
                </p>

                <p class="montserrat lh-lg">
                    We also grant you a limited, revocable, and nonexclusive license to create a hyperlink to any page
                    of the website for personal, non-commercial use only. A website that links to the website (i) may
                    link to, but not replicate, any and/or all of our Content; (ii) may not imply that we are endorsing
                    such website or its services or products; (iii) may not misrepresent its relationship with us; (iv)
                    may not contain content that could be construed as distasteful, obscene, offensive, controversial,
                    or illegal or inappropriate for any ages; (v) may not portray us or our products or services in a
                    false, misleading, derogatory, or otherwise offensive or objectionable manner, or associate us with
                    undesirable products, services, or opinions. We may, in our sole discretion, request that you remove
                    any link to the website, and upon receipt of such request, you shall immediately remove such link
                    and cease any linking unless separately and expressly authorized in writing by us to resume linking.
                </p>

                <p class="montserrat lh-lg">
                    Any unauthorized use by you of our website or any and/or all of our Content automatically terminates
                    the limited licenses set forth in this Section without prejudice to any other remedy provided by
                    applicable law or these Terms and Conditions.
                </p>

                <h5 class="montserrat fw-bold mt-5">Your Obligations And Responsibilities</h5>
                <p class="montserrat lh-lg">
                    You shall comply with these Terms and Conditions and the special warnings or instructions for access
                    or use posted on the website. You may not make any change or alteration to the website or any
                    Content or services that may appear on this website and may not impair in any way the integrity or
                    operation of the website. Without limiting the generality of any other provision of these Terms and
                    Conditions, if you default negligently or willfully in any of the obligations set forth in these
                    Terms and Conditions, you shall be liable for all the losses and damages that this may cause to
                    Fragnance, our Affiliates, partners, or licensors.
                </p>


                <h5 class="montserrat fw-bold mt-5">Special Features, Functionality And Events</h5>
                <p class="montserrat lh-lg">
                    Fragnance may offer certain special features and functionality or events (such as contests,
                    promotions, or other offerings) which may (a) be subject to terms of use, rules, and/or policies in
                    addition to or in lieu of these Terms and Conditions; and (b) be offered by us or by third parties.
                    If you choose to take advantage of these offerings, you agree that your use of those offerings will
                    be subject to such additional or separate terms of use, rules, and/or policies.
                </p>

                <h5 class="montserrat fw-bold mt-5">User Content</h5>
                <p class="montserrat lh-lg">
                    When you transmit, upload, post, e-mail, or otherwise make available data, text, software, music,
                    sound, photographs, graphics, images, videos, messages, or other materials ("User Content") on the
                    website, you are entirely responsible for such User Content. Such User Content constitutes a
                    Submission under Section 10 above. This means that all third parties, and not we, are entirely
                    responsible for all User Content that they post to the website. You agree not to engage in or assist
                    or encourage others to engage in transmitting, uploading, posting, e-mailing, or otherwise making
                    available on the website User Content that (a) is unlawful, harmful, threatening, abusive,
                    harassing, tortious, defamatory, vulgar, obscene, pornographic, libelous, invasive of another's
                    privacy, hateful, or racially, ethnically or otherwise objectionable; (b) you do not have a right to
                    make available under any law or under contractual or fiduciary relationships; (c) is known by you to
                    be false, inaccurate, or misleading; (d) you were compensated for or granted any consideration by
                    any third party; or (e) infringes any patent, trademark, trade secret, copyright, or other
                    proprietary and/or intellectual property rights of any party. In addition, you agree not to
                    transmit, upload, post, e-mail, or otherwise make available any software viruses, unsolicited or
                    unauthorized advertising, solicitation, or promotional material, including chain letters, mass
                    mailings, or any form of "spam." You further agree not to (i) impersonate any person or entity, or
                    falsely state or otherwise misrepresent your affiliation with any person or entity; (ii) "stalk" or
                    otherwise harass including advocating harassment of another, entrap or harm any third party
                    including harming minors in any way; (iii) forge headers or otherwise manipulate identifiers in
                    order to disguise the origin of any User Content; (iv) intentionally or unintentionally violate any
                    applicable local, state, national, or international law; or (v) collect or store personally
                    identifiable data about other users.
                </p>
                <p class="montserrat lh-lg">
                    We do not endorse or control the User Content transmitted or posted on the Fragnance website and
                    therefore, we do not guarantee the accuracy, integrity, or quality of User Content. You understand
                    that by using this website, you may be exposed to User Content that is offensive, indecent, or
                    objectionable to you. Under no circumstances will we be liable in any way for any User Content,
                    including, without limitation, for any errors or omissions in any User Content, or for any loss or
                    damage of any kind incurred by you as a result of the use of any User Content transmitted, uploaded,
                    posted, e-mailed, or otherwise made available via the website.
                </p>
                <p class="montserrat lh-lg">
                    You acknowledge that we have the right (but not the obligation) in our sole discretion to refuse to
                    post or remove any User Content, and we reserve the right to change, condense, or delete any User
                    Content. Without limiting the generality of the foregoing or any other provision of these Terms and
                    Conditions, we have the right to remove any User Content that violates these Terms and Conditions or
                    is otherwise objectionable, and we reserve the right to refuse service without prior notice for any
                    users who violate these Terms and Conditions or infringe the rights of others.
                </p>

                <h5 class="montserrat fw-bold mt-5">Copyright Complaints</h5>
                <p class="montserrat lh-lg">
                    We respect the intellectual property of others. If you believe that copyrighted materials have been
                    copied in a way that constitutes copyright infringement, please send an email or written notice to
                    us for notices of infringement and provide the following: (i) identification of the copyrighted
                    work(s) that you claim has been infringed and that you are the copyright owner or authorized to act
                    on the copyright owner's behalf; (ii) a description of the material that you claim is infringing and
                    the location of the material on the website; (iii) your address, telephone number, and email address
                    to: <a href="mailto:ecomm@fragnance.in">ecomm@fragnance.in</a>
                </p>

                <h5 class="montserrat fw-bold mt-5">Representations And Warranties And Limitation Of Liability</h5>
                <p class="montserrat lh-lg">
                    Fragnance website is presented "As Is." We make no representations or warranties of any kind
                    whatsoever, express or implied, in connection with these Terms and Conditions or the site, including
                    but not limited to warranties of merchantability, non-infringement, or fitness for a particular
                    purpose.
                </p>
                <p class="montserrat lh-lg">
                    You agree that, to the fullest extent permitted by applicable law, we will not be responsible or
                    liable (whether in contract, tort (including negligence) or otherwise), under any circumstances, for
                    any (a) interruption of business; (b) access delays or access interruptions to the site; (c) data
                    non-delivery, mis-delivery, corruption, destruction or other modification; (d) loss or damages of
                    any sort incurred as a result of dealings with or the presence of off-website links on the website;
                    (e) computer viruses, system failures or malfunctions which may occur in connection with your use of
                    the site, including during hyperlink to or from third-party websites; (f) any inaccuracies or
                    omissions in content, or (g) events beyond our reasonable control.
                </p>
                <p class="montserrat lh-lg">
                    Fragnance products are based on genuine and authentic formulations. Though enormous efforts are made
                    and precautions taken to render the products absolutely safe for human use, it is possible that
                    certain ingredients may cause allergic reactions to certain individuals or adversely affect
                    individuals with pre-existing medical conditions. Please make yourself aware of the ingredients and
                    usage instructions accompanying each of our products to make sure that they are safe for you to use.
                    It will be your sole responsibility to take proper precaution/professional medical/dermatological
                    advice before using any of our personal care products that you may be allergic to. You agree that
                    Fragnance will not be responsible or liable for any product-related issues, including without
                    limitation any allergic reactions to you on account of usage of our products. For any purchases made
                    through the Fragnance website, you will inter alia be governed by the limitation of liability and
                    disclaimer conditions provided in more detail with the product packaging/leaflets.
                </p>
                <p class="montserrat lh-lg">
                    Further, to the fullest extent permitted by law, we will not be liable for any indirect, special,
                    punitive, incidental, or consequential damages of any kind (including lost profits) related to the
                    website or your use thereof regardless of the form of action whether in contract, tort (including
                    negligence), or otherwise, even if we have been advised of the possibility of such damages and in no
                    event shall our maximum aggregate liability exceed Indian Rupees 1000 only.
                </p>
                <p class="montserrat lh-lg">
                    You agree that no claims or action arising out of, or related to, the use of the website or these
                    Terms and Conditions may be brought by you more than one (1) year after the cause of action relating
                    to such claim or action arose.
                </p>


                <h5 class="montserrat fw-bold mt-5">Indemnification</h5>
                <p class="montserrat lh-lg">
                    You agree to defend, indemnify and hold us harmless for any loss, damages or costs, including
                    reasonable attorneys' fees, resulting from any third-party claim, action, or demand resulting from
                    your use of Fragnance or breach of these Terms and Conditions. You also agree to indemnify us for
                    any loss, damages, or costs, including reasonable attorneys' fees, resulting from your use of
                    software robots, spiders, crawlers, or similar data-gathering and extraction tools, or any other
                    action you take that imposes an unreasonable burden or load on our infrastructure.
                </p>


                <h5 class="montserrat fw-bold mt-5">Disputes</h5>
                <p class="montserrat lh-lg">
                    With respect to any dispute regarding the website, all rights and obligations and all actions
                    contemplated by these Terms and Conditions shall be governed by the laws of India and the courts of
                    Ahmedabad, India, as if the Terms and Conditions were a contract wholly entered into and wholly
                    performed within Ahmedabad, India. To the fullest extent permitted by applicable law, any dispute,
                    differences, or claim arising out of your visit to the Fragnance website shall be referred to the
                    sole Arbitrator appointed by the Executive Director of Fragnance in accordance with the law. The
                    venue of such arbitration shall be at Ahmedabad, India, and the award of the Arbitrator shall be
                    final and binding on all parties and may be entered as a judgment in any court of competent
                    jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these Terms
                    and Conditions shall be joined to an arbitration involving any other party subject to this Terms and
                    Conditions, whether through class arbitration proceedings or otherwise.
                </p>
                <p class="montserrat lh-lg">
                    To the extent arbitration is not permitted by applicable law, any dispute relating in any way to
                    your visit to the website shall be submitted to an appropriate court or other judicial body in
                    Ahmedabad, India, as applicable, without prejudice to the applicable law and all applicable
                    provisions of this Section, and subject to our right to seek injunctive or other appropriate relief
                    in any court, if you have in any manner violated or threatened to violate our intellectual property
                    rights and you consent to exclusive jurisdiction and venue in such courts.
                </p>


                <h5 class="montserrat fw-bold mt-5">Consent To Receive Notices Electronically By Posting On The Website
                    And Via Email</h5>
                <p class="montserrat lh-lg">
                    You consent to receive any agreements, notices, disclosures, and other communications (collectively,
                    "Notices") to which these Terms and Conditions refer from us electronically, including without
                    limitation by email or by posting notices on this website. You agree that all Notices that we
                    provide to you electronically satisfy any legal requirement that such communications be in writing
                    in English. To withdraw your consent to receive Notices electronically, you must notify us of your
                    withdrawal of such consent by emailing us at:  <a href="mailto:ecomm@fragnance.in">ecomm@fragnance.in</a> and discontinue your use of this
                    website.
                </p>
                <p class="montserrat lh-lg">
                    Please note that this consent to receive Notices is entirely separate from any election you may make
                    with respect to receipt of marketing communications. Your options with respect to receipt of
                    marketing communications are set forth in our Privacy Policy.
                </p>


                <h5 class="montserrat fw-bold mt-5">General</h5>
                <p class="montserrat lh-lg">
                    You acknowledge and agree that these Terms and Conditions constitute the complete and exclusive
                    agreement between us concerning your use of the website, and supersede and govern all prior
                    proposals, agreements, or other communications.
                </p>
                <p class="montserrat lh-lg">
                    We reserve the right, in our sole discretion, to change these Terms and Conditions at any time by
                    posting the changes on the website and providing notice of such change. Any changes are effective
                    immediately upon posting to the Site and release of notice of such change. Your continued use of the
                    website thereafter constitutes your agreement to all such changed Terms and Conditions. We may, with
                    or without prior notice, terminate any of the rights granted by these Terms and Conditions. You
                    shall comply immediately with any termination or other notice, including, as applicable, by ceasing
                    all use of the website.
                </p>
                <p class="montserrat lh-lg">
                    Nothing contained in these Terms and Conditions shall be construed as creating any agency,
                    partnership, or other form of joint enterprise between us. Our failure to require your performance
                    of any provision hereof shall not affect our full right to require such performance at any time
                    thereafter, nor shall our waiver of a breach of any provision hereof be taken or held to be a waiver
                    of the provision itself. In the event that any provision of these Terms and Conditions shall be
                    unenforceable or invalid under any applicable law or be so held by any applicable arbitral award or
                    court decision, such unenforceability or invalidity shall not render these Terms and Conditions
                    unenforceable or invalid as a whole but these Terms and Conditions shall be modified, to the extent
                    possible, by the adjudicating entity to most fully reflect the original intent of the parties as
                    reflected in the original provision.
                </p>


                <h5 class="montserrat fw-bold mt-5">B2G1 Offer</h5>
                <ol class="montserrat lh-lg">
                    <li>The Offer is applicable to all products available on the official Fragnance website.</li>
                    <li>The item(s) with the lowest price will be considered as FREE. If three identical items are not
                        ordered, the least expensive item will be deducted.</li>
                    <li>B2G1 offer is exclusive to the official website and is not valid on external marketplaces where
                        Fragnance products are sold.</li>
                    <li>Offer details may change or be discontinued without prior notice, with the consent of Fragnance.
                    </li>
                    <li>Offers are non-transferable and cannot be exchanged, sold, or bartered for cash.</li>
                    <li>Products can be mixed and matched but must be purchased in multiples of 3 to qualify.</li>
                    <li>If the lower-priced product is returned (subject to return eligibility), a refund will be issued
                        based on the amount paid. If the higher-priced product is returned (subject to return
                        eligibility), the refund will be calculated based on the amount paid, minus the discount applied
                        to the lower-priced product.</li>
                    <li>No price adjustments will be made for prior purchases.</li>
                    <li>If the B2G1 coupon code is not applied at checkout, the customer will not be eligible for an
                        additional product or discount after the purchase.</li>
                    <li>Offer valid until stocks last.</li>
                </ol>


                <h5 class="montserrat fw-bold mt-5">Grievance Officer</h5>
                <p class="montserrat lh-lg">
                    The name and contact details of the Grievance Officer to handle any complaints in relation to the
                    sale of Products or use of this Website are provided below. All complaints will be acknowledged
                    within 48 hours (Working Days) and will be addressed no later than 1 month from the date of
                    complaint received.
                </p>
                <p class="montserrat lh-lg">
                    Name - Govind Mishra<br>
                    Email: <a href="mailto:govind.mishra@fragnance.in">govind.mishra@fragnance.in</a><br>
                    Time: Monday-Saturday (From 11:00 Am to 6:00pm)
                </p>
                <p class="montserrat lh-lg">
                    The user shall not assign its rights or obligations under these Terms and the Privacy Policy to a
                    third party.
                </p>
                <p class="montserrat lh-lg">
                    If you have any questions regarding these Terms and Conditions, please email us at:
                    <a href="mailto:ecomm@fragnance.in">ecomm@fragnance.in</a>
                </p>
                <p class="montserrat lh-lg">
                    Worldwide Copyright © Fragnance. (brand owners Fragnance). All worldwide rights reserved.
                </p>

<!-- 
                <h5 class="montserrat fw-bold mt-5"></h5>
                <p class="montserrat lh-lg">

                </p>


                <h5 class="montserrat fw-bold mt-5"></h5>
                <p class="montserrat lh-lg">

                </p>


                <h5 class="montserrat fw-bold mt-5"></h5>
                <p class="montserrat lh-lg">

                </p> -->
            </div>

        </div>

    </div>

    <!-- Footer Code Include  -->

    <?php $this->load->view('include/Footer'); ?>

</body>

</html>